### ISSUE TITLE
Use FileNotFoundError

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/pykern#109]
https://www.python.org/dev/peps/pep-3151/ (py3.3) introduced FileNotFoundError. I think `pkio.exception_is_not_found` can be changed to use it and in new code we can just catch FileNotFoundError directly.

```
from pykern import pkio


try:
    with open('/xxyyzz') as f:
        raise AssertionError('should be ENOENT')
except Exception as e:
    assert pkio.exception_is_not_found(e)
    assert isinstance(e, FileNotFoundError)
```

**Comment by e-carlin** [comment]
You're right. At least py.path doesn't work. Annoying...

```
from pykern import pkio

p = pkio.py_path('/foo')
assert not p.check()

try:
    p.move(pkio.py_path('/bar'))
except Exception as e:
    assert pkio.exception_is_not_found(e)
    assert isinstance(e, FileNotFoundError)
```

```
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/py/_error.py", line 66, in checked_call
    return func(*args, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/foo' -> '/bar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "x.py", line 7, in <module>
    p.move(pkio.py_path('/bar'))
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/py/_path/common.py", line 213, in move
    self.rename(target)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/py/_path/local.py", line 459, in rename
    return py.error.checked_call(os.rename, self.strpath, target)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/py/_error.py", line 86, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.ENOENT: [No such file or directory]: rename('/foo', '/bar')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "x.py", line 10, in <module>
    assert isinstance(e, FileNotFoundError)
AssertionError
```
