### ISSUE TITLE
github_bkp radiasoft-sirepo.git/gc.pid: File removed before we read it

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#163]
This needs investigating. It doesn't seem like there were two backup processes running.

```
03:02:39 pykern/pkcli/github.py:365:__init__ radiasoft/sirepo: begin
03:05:04 pykern/pkcli/github.py:476:_repo ERROR: radiasoft/sirepo <class 'subprocess.CalledProcessError'> Command '['tar', 'cJf', 'radiasoft-sirepo.git.txz', 'radiasoft-sirepo.git']' returned non-zero exit status 1. b'tar: radiasoft-sirepo.git/gc.pid: File removed before we read it
03:05:04 tar: radiasoft-sirepo.git/gc.log.lock: File removed before we read it
03:05:04 tar: radiasoft-sirepo.git: file changed as we read it
03:05:04 ' Traceback (most recent call last):
03:05:04 pykern/pkcli/github.py", line 459, in _repo
03:05:04 _clone('.git')
03:05:04 pykern/pkcli/github.py", line 405, in _clone
03:05:04 _tar(base)
03:05:04 pykern/pkcli/github.py", line 444, in _tar
03:05:04 _shell(['tar', 'cJf', base + _TXZ, base])
03:05:04 pykern/pkcli/github.py", line 582, in _shell
03:05:04 subprocess.check_output(cmd, stderr=subprocess.STDOUT)
03:05:04 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 395, in check_output
03:05:04 **kwargs).stdout
03:05:04 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 487, in run
03:05:04 output=stdout, stderr=stderr)
03:05:04 subprocess.CalledProcessError: Command '['tar', 'cJf', 'radiasoft-sirepo.git.txz', 'radiasoft-sirepo.git']' returned non-zero exit status 1.
03:05:04 Exception was printed at:
03:05:04 subprocess.CalledProcessError: Command '['tar', 'cJf', 'radiasoft-sirepo.git.txz', 'radiasoft-sirepo.git']' returned non-zero exit status 1.
03:05:04 File "/home/vagrant/.pyenv/versions/py3/bin/pykern", line 8, in <module>
03:05:04 sys.exit(main())
03:05:04 pykern/pykern_console.py", line 17, in main
03:05:04 return pkcli.main('pykern')
03:05:04 pykern/pkcli/__init__.py", line 143, in main
03:05:04 res = argh.dispatch(parser, argv=argv)
03:05:04 argh/dispatching.py", line 174, in dispatch
03:05:04 for line in lines:
03:05:04 argh/dispatching.py", line 277, in _execute_command
03:05:04 for line in result:
03:05:04 argh/dispatching.py", line 260, in _call
03:05:04 result = function(*positional, **keywords)
03:05:04 pykern/pkcli/github.py", line 42, in backup
03:05:04 _Backup()
03:05:04 pykern/pkcli/github.py", line 366, in __init__
03:05:04 self._repo(r)
```

**Comment by robnagler** [comment]
Perhaps two backups were running at the same time?

**Comment by robnagler** [comment]
It happened yesterday. It only happens on Sirepo. This time a different file  radiasoft-sirepo.git/gc.log.lock.

**Comment by robnagler** [comment]
Hasn't happened again.
