### ISSUE TITLE
Understand fix #173

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#174]
#173 fixes something. We should know why.

**Comment by robnagler** [comment]
I'm getting this in pkunit_test:

```
Traceback (most recent call last):
  File "/Users/nagler/src/radiasoft/pykern/tests/pkunit_test.py", line 104, in test_pkexcept
    with pkexcept(KeyError, 'xyzzy'):
  File "/Users/nagler/.pyenv/versions/3.10.3/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/Users/nagler/src/radiasoft/pykern/pykern/pkunit.py", line 274, in pkexcept
    pkfail(*fmt_and_args, **kwargs)
  File "/Users/nagler/src/radiasoft/pykern/pykern/pkunit.py", line 305, in pkfail
    raise PKFail('{} {}'.format(call, msg))
pykern.pkunit.PKFail: tests/pkunit_test.py:104:test_pkexcept xyzzy

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nagler/src/radiasoft/pykern/tests/pkunit_test.py", line 108, in test_pkexcept
    assert 'pkunit_test.py:{}:test_pkexcept'.format(lineno) in str(e.args)
AssertionError: assert 'pkunit_test.py:105:test_pkexcept' in "('tests/pkunit_test.py:104:test_pkexcept xyzzy',)"
 +  where 'pkunit_test.py:105:test_pkexcept' = <built-in method format of str object at 0x101525b10>(105)
 +    where <built-in method format of str object at 0x101525b10> = 'pkunit_test.py:{}:test_pkexcept'.format
 +  and   "('tests/pkunit_test.py:104:test_pkexcept xyzzy',)" = str(('tests/pkunit_test.py:104:test_pkexcept xyzzy',))
 +    where ('tests/pkunit_test.py:104:test_pkexcept xyzzy',) = PKFail('tests/pkunit_test.py:104:test_pkexcept xyzzy').args
```

**Comment by robnagler** [comment]
False alarm. This is a 3.10 change: AssertionError.args no longer includes line.
