### ISSUE TITLE
pksubprocess_test.py::test_check_call_with_signals "randomly" failing

### ISSUE THREAD

**Issue by rorour** [radiasoft/pykern#250]
pksubprocess_test.py::test_check_call_with_signals "randomly" failing in github ci environment, but not locally.

```
tests/pksubprocess_test.py::test_check_call_with_signals FAILED
=================================== FAILURES ===================================
_________________________ test_check_call_with_signals _________________________
Traceback (most recent call last):
  File "/home/runner/work/pykern/pykern/tests/pksubprocess_test.py", line 65, in test_check_call_with_signals
    pksubprocess.check_call_with_signals(cmd, output=o, msg=msg)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/_pytest/python_api.py", line 966, in __exit__
    fail(self.message)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/_pytest/outcomes.py", line 196, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: DID NOT RAISE <class 'RuntimeError'>
============================== 1 failed in 10.14s ==============================
```

**Comment by robnagler** [comment]
no longer an issue
