### ISSUE TITLE
allow pkcli to execute python files `pykern foo.py`

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#277]
When you say, e.g. `python server.py`, it gets this error:

```txt
Traceback (most recent call last):
  File "sirepo/server.py", line 12, in <module>
    from sirepo import simulation_db
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 15, in <module>
    from sirepo import srschema
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/srschema.py", line 11, in <module>
    from sirepo import util
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/util.py", line 26, in <module>
    import werkzeug.utils
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/werkzeug/__init__.py", line 1, in <module>
    from .serving import run_simple as run_simple
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 31, in <module>
    from .exceptions import InternalServerError
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/werkzeug/exceptions.py", line 50, in <module>
    from html import escape
ImportError: cannot import name 'escape' from 'html' (/home/vagrant/src/radiasoft/sirepo/sirepo/html.py)
```

#203 fixed this, but it only works for pkcli programs.

Change pkcli to look if the module ends in `.py`, and then import the module, possibly with a message "compiling module.py".

**Comment by robnagler** [comment]
dup #204
