### ISSUE TITLE
AttributeError: module 'argcomplete' has no attribute 'autocomplete'

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#296]
```txt
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 33, in <module>
    sys.exit(load_entry_point('sirepo', 'console_scripts', 'sirepo')())
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main("sirepo")
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcli/__init__.py", line 157, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 133, in dispatch
    autocomplete(parser)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/completion.py", line 92, in autocomplete
    argcomplete.autocomplete(parser)
AttributeError: module 'argcomplete' has no attribute 'autocomplete'
```

**Comment by robnagler** [comment]
Fix `rm -rf /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argcomplete`

argcomplete is gone, apparently, and the pyc files were still there.
