### ISSUE TITLE
20221018: JSONDecodeError on py3.10

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/pykern#304]
```
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcollections.py", line 331, in json_load_any
    return json.loads(obj.read() if hasattr(obj, "read") else obj, *args, **kwargs)
  File "/home/vagrant/.pyenv/versions/3.10.5/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'
```

**Comment by e-carlin** [comment]
@robnagler the docs say
```
Changed in version 3.6: s can now be of type [bytes](https://docs.python.org/3/library/stdtypes.html#bytes) or [bytearray](https://docs.python.org/3/library/stdtypes.html#bytearray). The input encoding should be UTF-8, UTF-16 or UTF-32.

Changed in version 3.9: The keyword argument encoding has been removed.
```

The econding is set by reading the charset in sirepo
https://github.com/radiasoft/sirepo/blob/82cb6e6028467a85bb1ca93d1579f54871b37261/sirepo/http_request.py#L52

Maybe we continue to pass the encoding through and have pkcollections.json_load_any remove the kwarg and assert it is (None, UTF-8, UTF-16, UTF-32) ?

**Comment by e-carlin** [comment]
Ugh, more json errors
```
Oct 17 23:43:50 36867     0 sirepo/server.py:383:api_importFile srw_3_deviance.json: exception: Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 357, in api_importFile
    data = sirepo.importer.read_json(req.file_stream.read(), self, req.type)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/importer.py", line 54, in read_json
    data = simulation_db.json_load(text)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 318, in json_load
    return pkcollections.json_load_any(*args, **kwargs)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcollections.py", line 331, in json_load_any
    return json.loads(obj.read() if hasattr(obj, "read") else obj, *args, **kwargs)
  File "/home/vagrant/.pyenv/versions/3.10.5/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/home/vagrant/.pyenv/versions/3.10.5/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/vagrant/.pyenv/versions/3.10.5/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by robnagler** [comment]
> Maybe we continue to pass the encoding through and have pkcollections.json_load_any remove the kwarg and assert it is (None, UTF-8, UTF-16, UTF-32) ?

I think this is a red herring. It can be removed. We don't set it elsewhere. It was [this before](https://github.com/radiasoft/sirepo/blame/deddf190492845b10b0afb89dfd1c5379d00bd34/sirepo/http_request.py#L44), which was incorrect since it's what we are reading from disk, not what we are getting from the client. 

I removed it in my code. Running the test suite now, which seems to be passing.
