### ISSUE TITLE
20230228 import pykern error

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#339]
`import pykern` yields:

```
Traceback (most recent call last):
  File "t.py", line 1, in <module>
    import pykern
  File "/home/vagrant/src/radiasoft/pykern/pykern/__init__.py", line 8, in <module>
    import pkg_resources
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 84, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 10, in <module>
    from pkg_resources.extern.pyparsing import (  # noqa
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/pkg_resources/extern/__init__.py", line 52, in create_module
    return self.load_module(spec.name)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/pkg_resources/extern/__init__.py", line 48, in load_module
    "distribution.".format(**locals())
ImportError: The 'pyparsing' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
```

**Comment by e-carlin** [comment]
I've seen this before. I believe an uninstall of pykern and installing again "fixes" the problem.

I have a hunch that installing some other package that we use is causing this problem. No data to back this up other than I've seen this appear after installing "things".

**Comment by robnagler** [comment]
I'll debug a little today then since my install is messed up.

**Comment by robnagler** [comment]
It's a stupid problem. It's based on the fact that python puts "." in the path automatically so that "html" gets found. The error is [obscured here](https://github.com/pypa/pkg_resources/blob/0ff92f58b264a2ff759b5db374cfb05902a718cc/pkg_resources/extern/__init__.py#L55):

```py
            except ImportError:
                pass
        else:
            raise ImportError(
                "The '{target}' package is required; "
                "normally this is bundled with this package so if you get "
                "this warning, consult the packager of your "
                "distribution.".format(**locals())
            )
```

pyparsing imports html. sirepo.html exists and I was running "t.py" in sirepo/sirepo/. #204 will fix this.

**Comment by e-carlin** [comment]
How many times will that "feature" bite us...
