### ISSUE TITLE
beamsim build pykern tests failed

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/pykern#347]
```
tests/xlsx_test.pyerror: FAILED=1 passed=38
 FAIL tests/xlsx_test.log
============================= test session starts ==============================
platform linux -- Python 3.7.2, pytest-7.1.2, pluggy-1.0.0 -- /home/vagrant/.pyenv/versions/3.7.2/envs/py3/bin/python
cachedir: .pytest_cache
rootdir: /home/vagrant/src/radiasoft/pykern
collecting ... collected 1 item

tests/xlsx_test.py::test_1 FAILED

=================================== FAILURES ===================================
____________________________________ test_1 ____________________________________
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/pykern/tests/xlsx_test.py", line 22, in test_1
    for d in pykern.pkunit.case_dirs():
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 179, in case_dirs
    _compare(i, w)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 168, in _compare
    file_eq(expect_path=e, actual_path=a, ignore_lines=ignore_lines)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 265, in file_eq
    _FileEq(expect_path, *args, **kwargs)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 488, in __init__
    self._compare()
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 587, in _compare
    pkfail("expect != actual:\n{}", _failed_msg(p))
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 394, in pkfail
    raise PKFail("{} {}".format(call, msg))
pykern.pkunit.PKFail: tests/xlsx_test.py:22:test_1 expect != actual:
'diff' '/home/vagrant/src/radiasoft/pykern/tests/xlsx_data/2.out/xl/styles.xml' '/home/vagrant/src/radiasoft/pykern/tests/xlsx_work/2/xl/styles.xml'
2c2
< <styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="2"><numFmt numFmtId="164" formatCode="@"/><numFmt numFmtId="165" formatCode="$#,##0"/></numFmts><fonts count="2"><font><sz val="11"/><color theme="1"/><name val="Calibri"/><family val="2"/><scheme val="mino\
r"/></font><font><b/><sz val="11"/><color theme="1"/><name val="Calibri"/><family val="2"/><scheme val="minor"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="2"><border><left/><right/><top/><bottom\
/><diagonal/></border><border><left/><right/><top style="thin"><color auto="1"/></top><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="6"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf \
numFmtId="164" fontId="1" fillId="0" borderId="0" xfId="0" applyNumberFormat="1" applyFont="1"/><xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/><xf numFmtId="165" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/><xf numFmtId="164" fontId="0" fill\
Id="0" borderId="1" xfId="0" applyNumberFormat="1" applyBorder="1"/><xf numFmtId="165" fontId="0" fillId="0" borderId="1" xfId="0" applyNumberFormat="1" applyBorder="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles><dxfs count="0"/><tableStyles count="0\
" defaultTableStyle="TableStyleMedium9" defaultPivotStyle="PivotStyleLight16"/></styleSheet>
\ No newline at end of file
---
> <styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="2"><numFmt numFmtId="164" formatCode="@"/><numFmt numFmtId="164" formatCode="@"/><numFmt numFmtId="165" formatCode="$#,##0"/><numFmt numFmtId="164" formatCode="@"/><numFmt numFmtId="165" formatCode="$#,##0"\
/></numFmts><fonts count="2"><font><sz val="11"/><color theme="1"/><name val="Calibri"/><family val="2"/><scheme val="minor"/></font><font><b/><sz val="11"/><color theme="1"/><name val="Calibri"/><family val="2"/><scheme val="minor"/></font></fonts><fills count="2"><fill><patternFill patternType="none\
"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="2"><border><left/><right/><top/><bottom/><diagonal/></border><border><left/><right/><top style="thin"><color auto="1"/></top><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fil\
lId="0" borderId="0"/></cellStyleXfs><cellXfs count="6"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="164" fontId="1" fillId="0" borderId="0" xfId="0" applyNumberFormat="1" applyFont="1"/><xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"\
/><xf numFmtId="165" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/><xf numFmtId="164" fontId="0" fillId="0" borderId="1" xfId="0" applyNumberFormat="1" applyBorder="1"/><xf numFmtId="165" fontId="0" fillId="0" borderId="1" xfId="0" applyNumberFormat="1" applyBorder="1"/></cellXfs>\
<cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles><dxfs count="0"/><tableStyles count="0" defaultTableStyle="TableStyleMedium9" defaultPivotStyle="PivotStyleLight16"/></styleSheet>
\ No newline at end of file


to update test data:
        cp '/home/vagrant/src/radiasoft/pykern/tests/xlsx_work/2/xl/styles.xml' '/home/vagrant/src/radiasoft/pykern/tests/xlsx_data/2.out/xl/styles.xml'
```

**Comment by robnagler** [comment]
I think this is due to the version of xlswriter. If you rebuild common, it probably will fix things.

**Comment by e-carlin** [comment]
Thanks, rebuilding common fixed it.
