### ISSUE TITLE
tests/xlsx_test.py::test_1 pykern/pkunit.py:741:_pkdlog ERROR converting xlsx to csv

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/pykern#363]
```
____________________________________ test_1 ____________________________________
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/pykern/tests/xlsx_test.py", line 22, in test_1
    for d in pykern.pkunit.case_dirs():
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 188, in case_dirs
    _compare(i, w)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 173, in _compare
    file_eq(
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 277, in file_eq
    _FileEq(expect_path, *args, **kwargs)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 517, in __init__
    self._set_expect_and_actual()
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 667, in _set_expect_and_actual
    if self._expect_csv():
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 622, in _expect_csv
    self._actual_xlsx()
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 529, in _actual_xlsx
    self._actual_xlsx_to_csv(b, s)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 550, in _actual_xlsx_to_csv
    p.to_csv(
TypeError: to_csv() got an unexpected keyword argument 'line_terminator'
```

**Comment by e-carlin** [comment]
It was renamed to lineterminator https://pandas.pydata.org/docs/whatsnew/v2.0.0.html#backwards-incompatible-api-changes ...
