### ISSUE TITLE
github_bkp silence errors related to missing wiki

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/pykern#367]
Many of our repos don't have wikis. When we try to back them up errors are produced because the repo can't be found. This clogs up the logs and makes real errors harder to find. Ideally, we should perform a check to see if a repo doesn't exist and not try to clone it. 

Example of the error:
```
03:01:57 pykern/pkcli/github.py:536:_repo ERROR: radiasoft/opal <class 'subprocess.CalledProcessError'> Command '('git', 'clone', '--quiet', '--mirror', 'https://github.com/radiasoft/opal.wiki.git', 'radiasoft-opal.wiki.git')' returned non-zero exit status 128. b"remote: Repository not found.
03:01:57 fatal: repository 'https://github.com/radiasoft/opal.wiki.git/' not found
03:01:57 " Traceback (most recent call last):
03:01:57 pykern/pkcli/github.py", line 528, in _repo
03:01:57 _clone(".wiki.git")
03:01:57 pykern/pkcli/github.py", line 457, in _clone
03:01:57 _shell(
03:01:57 pykern/pkcli/github.py", line 639, in _shell
03:01:57 subprocess.check_output(cmd, stderr=subprocess.STDOUT)
03:01:57 File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/subprocess.py", line 424, in check_output
03:01:57 return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
03:01:57 File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/subprocess.py", line 528, in run
03:01:57 raise CalledProcessError(retcode, process.args,
03:01:57 subprocess.CalledProcessError: Command '('git', 'clone', '--quiet', '--mirror', 'https://github.com/radiasoft/opal.wiki.git', 'radiasoft-opal.wiki.git')' returned non-zero exit status 128.
03:01:57 Exception was printed at:
03:01:57 subprocess.CalledProcessError: Command '('git', 'clone', '--quiet', '--mirror', 'https://github.com/radiasoft/opal.wiki.git', 'radiasoft-opal.wiki.git')' returned non-zero exit status 128.
03:01:57 File "/home/vagrant/.pyenv/versions/py3/bin/pykern", line 8, in <module>
03:01:57 sys.exit(main())
03:01:57 pykern/pykern_console.py", line 17, in main
03:01:57 return pkcli.main("pykern")
03:01:57 pykern/pkcli/__init__.py", line 158, in main
03:01:57 res = argh.dispatch(parser, argv=argv)
03:01:57 argh/dispatching.py", line 179, in dispatch
03:01:57 for line in lines:
03:01:57 argh/dispatching.py", line 290, in _execute_command
03:01:57 for line in result:
03:01:57 argh/dispatching.py", line 273, in _call
03:01:57 result = function(*positional, **keywords)
03:01:57 pykern/pkcli/github.py", line 117, in backup
03:01:57 _Backup()
03:01:57 pykern/pkcli/github.py", line 430, in __init__
03:01:57 self._repo(r)
```

**Comment by robnagler** [comment]
@Benbenbenin0 this is another small task that would be good to get done.
