### ISSUE TITLE
py3 pkdebug stack traces need special truncation

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#66]
This is particularly true for a wrapped request in sirepo. The stack trace prints the `Exception was printed at:` part, but should trim that, because it's useless except perhaps the last few lines.

Workaround:

```sh
PYKERN_PKDEBUG_MAX_STRING=100000 pykern test test_cookie2.py
```

I lost this trace:

```txt
../sirepo/uri_router.py:93:call_api api=<function api_srUnit at 0x7f3bfde4b620> exception= stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 85, in call_api
    r = flask.make_response(f(**kwargs) if kwargs else f())
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 502, in api_srUnit
    v.op()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/srunit.py", line 157, in <lambda>
    return test_in_request(lambda: func(), **kwargs)
  File "/home/vagrant/src/radiasoft/sirepo/tests/cookie2_test.py", line 27, in test_set_get
    cookie.set_value('hi4', 'hello')
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/cookie.py", line 83, in set_value
    value = pkcompat.from_bytes(value)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcompat.py", line 55, in _from_bytes
    assert isinstance(value, bytes)
AssertionError

Exception was printed at:

AssertionError
  File "/home/vagrant/.pyenv/versions/py3/bin/py.test", line 8, in <module>
    sys.exit(main())
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/_pytest/config/__init__.py", line 125, in main
    config=config
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
```

**Comment by robnagler** [comment]
@e-carlin this is related to https://github.com/radiasoft/sirepo/issues/3933. I couldn't see what the message was without actually putting in the stack trace in import_module and then setting PYKERN_PKDEBUG_MAX_STRING=1000000.
Definitely not a priority just noting
