### ISSUE TITLE
pksetup pip installation error with Python 3

### ISSUE THREAD

**Issue by elventear** [radiasoft/pykern#8]
When issuing `pip install` for a module packaged with `pksetup`, we get the following error: `    TypeError: Can't mix strings and bytes in path components`. 

Full traceback:
```
  Running setup.py install for rslinac ... error
    Complete output from command /tmp/test/35/venv/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/var/folders/63/3jkz49w174x2r847ttp6whgr0000gn/T/pip-h4bkoqui-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/63/3jkz49w174x2r847ttp6whgr0000gn/T/pip-w1xvs2r3-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/test/35/venv/bin/../include/site/python3.5/rslinac:
    running install
    running build
    running build_py
    creating build/lib.macosx-10.11-x86_64-3.5/rslinac
    copying rslinac/__init__.py -> build/lib.macosx-10.11-x86_64-3.5/rslinac
    copying rslinac/base_pkconfig.py -> build/lib.macosx-10.11-x86_64-3.5/rslinac
    copying rslinac/beam_solver.py -> build/lib.macosx-10.11-x86_64-3.5/rslinac
    copying rslinac/rslinac_console.py -> build/lib.macosx-10.11-x86_64-3.5/rslinac
    creating build/lib.macosx-10.11-x86_64-3.5/rslinac/pkcli
    copying rslinac/pkcli/__init__.py -> build/lib.macosx-10.11-x86_64-3.5/rslinac/pkcli
    copying rslinac/pkcli/beam_solver.py -> build/lib.macosx-10.11-x86_64-3.5/rslinac/pkcli
    running egg_info
    writing requirements to rslinac.egg-info/requires.txt
    writing top-level names to rslinac.egg-info/top_level.txt
    writing rslinac.egg-info/PKG-INFO
    writing dependency_links to rslinac.egg-info/dependency_links.txt
    writing entry points to rslinac.egg-info/entry_points.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'rslinac.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'rslinac.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/folders/63/3jkz49w174x2r847ttp6whgr0000gn/T/pip-h4bkoqui-build/setup.py", line 63, in <module>
        extra_compile_args=get_compile_args(),
      File "/tmp/test/35/venv/lib/python3.5/site-packages/pykern/pksetup.py", line 377, in setup
        op(**base)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/test/35/venv/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/test/35/venv/lib/python3.5/site-packages/setuptools/command/build_py.py", line 53, in run
        self.build_package_data()
      File "/tmp/test/35/venv/lib/python3.5/site-packages/setuptools/command/build_py.py", line 118, in build_package_data
        for package, src_dir, build_dir, filenames in self.data_files:
      File "/tmp/test/35/venv/lib/python3.5/site-packages/setuptools/command/build_py.py", line 66, in __getattr__
        self.data_files = self._get_data_files()
      File "/tmp/test/35/venv/lib/python3.5/site-packages/setuptools/command/build_py.py", line 83, in _get_data_files
        return list(map(self._get_pkg_data_files, self.packages or ()))
      File "/tmp/test/35/venv/lib/python3.5/site-packages/setuptools/command/build_py.py", line 95, in _get_pkg_data_files
        for file in self.find_data_files(package, src_dir)
      File "/tmp/test/35/venv/lib/python3.5/site-packages/setuptools/command/build_py.py", line 114, in find_data_files
        return self.exclude_data_files(package, src_dir, files)
      File "/tmp/test/35/venv/lib/python3.5/site-packages/setuptools/command/build_py.py", line 198, in exclude_data_files
        files = list(files)
      File "/tmp/test/35/venv/lib/python3.5/site-packages/setuptools/command/build_py.py", line 234, in <genexpr>
        for pattern in raw_patterns
      File "/tmp/test/35/venv/bin/../lib/python3.5/posixpath.py", line 89, in join
        genericpath._check_arg_types('join', a, *p)
      File "/tmp/test/35/venv/bin/../lib/python3.5/genericpath.py", line 145, in _check_arg_types
        raise TypeError("Can't mix strings and bytes in path components") from None
    TypeError: Can't mix strings and bytes in path components

    ----------------------------------------
Command "/tmp/test/35/venv/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/var/folders/63/3jkz49w174x2r847ttp6whgr0000gn/T/pip-h4bkoqui-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/63/3jkz49w174x2r847ttp6whgr0000gn/T/pip-w1xvs2r3-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/test/35/venv/bin/../include/site/python3.5/rslinac" failed with error code 1 in /var/folders/63/3jkz49w174x2r847ttp6whgr0000gn/T/pip-h4bkoqui-build/
```

**Comment by robnagler** [comment]
There's also "warning: manifest_maker: standard file '-c' not found" which
may be related or a red herring.
