### ISSUE TITLE
test_check_call_with_signals sometimes fails with: DID NOT RAISE <type 'exceptions.RuntimeError'>

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#9]
The failure doesn't happen on my machine. It only seems to fail Travis when initiated by GitHub's webhook. If you restart the build, it works -- 
[complete failure log](https://github.com/radiasoft/pykern/files/464922/log.txt).

``` text
[31m[1m_________________________ test_check_call_with_signals _________________________[0m
def test_check_call_with_signals():
        from pykern import pksubprocess
        from pykern import pkunit
        import os
        import signal

        messages = []
        def msg(*args):
            s = args[0]
            messages.append(s.format(*args[1:]))

        signals = []
        def signal_handler(sig, frame):
            signals.append(sig)

        with pkunit.save_chdir_work():
            with open('true.out', 'w+') as o:
                pksubprocess.check_call_with_signals(['true'], output=o)
                o.seek(0)
                actual = o.read()
                assert '' == actual, \
                    'Expecting empty output "{}"'.format(actual)

            with open('echo.out', 'w+') as o:
                messages = []
                tag = 'xyzzy'
                pksubprocess.check_call_with_signals(['echo', tag], output=o, msg=msg)
                o.seek(0)
                actual = o.read()
                assert tag in actual, \
                    '"{}" not in output "{}"'.format(tag, actual)
                assert 'started' in messages[0], \
                    '"started" not in messages[0] "{}"'.format(messages[0])
                assert 'normal exit' in messages[1], \
                    '"normal exit" not in messages[1] "{}"'.format(messages[1])

            with open('kill.out', 'w+') as o:
                messages = []
                signals = []
                signal.signal(signal.SIGTERM, signal_handler)
                with open('kill.sh', 'w') as f:
                    f.write('kill -TERM {}\nsleep 10'.format(os.getpid()))
                cmd = ['sh', 'kill.sh']
                with pytest.raises(RuntimeError):
>                   pksubprocess.check_call_with_signals(cmd, output=o, msg=msg)
E                   Failed: DID NOT RAISE <type 'exceptions.RuntimeError'>

tests/pksubprocess_test.py:54: Failed
[31m[1m==================== 1 failed, 62 passed in 107.01 seconds =====================[0m
[31mERROR: InvocationError: '/home/travis/build/radiasoft/pykern/.tox/py27/bin/python setup.py build test'[0m
___________________________________ summary ____________________________________
[31mERROR:   py27: commands failed[0m
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    'Topic :: Utilities',
  File "/home/travis/build/radiasoft/pykern/pykern/pksetup.py", line 378, in setup
    op(**base)
  File "/opt/python/2.7.9/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/python/2.7.9/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/python/2.7.9/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/travis/build/radiasoft/pykern/pykern/pksetup.py", line 128, in run
    self.__run_cmd('tox')
  File "/home/travis/build/radiasoft/pykern/pykern/pksetup.py", line 162, in __run_cmd
    cmd.run()
  File "/home/travis/build/radiasoft/pykern/pykern/pksetup.py", line 273, in run
    subprocess.check_call(['tox'])
  File "/opt/python/2.7.9/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tox']' returned non-zero exit status 1

travis_time:end:10019841:start=1473455463574674540,finish=1473455597563051870,duration=133988377330
[0K
[31;1mThe command "python setup.py pkdeploy" exited with 1.[0m
```

**Comment by robnagler** [comment]
Not repeatable, and doesn't seem to be an issue any more
